# Generated by Django 5.0.6 on 2024-06-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0004_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=10, verbose_name='Ingrese precio producto'),
        ),
    ]
