# Generated by Django 5.0.6 on 2024-06-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0008_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[(0, 'Consulta'), (1, 'Reclamo'), (2, 'Sugerencia'), (3, 'Felicitaciones'), (4, 'Despacho'), (5, 'Devolución'), (6, 'Objeto dañado')]),
        ),
    ]
