# Generated by Django 5.0.6 on 2025-05-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0010_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='stock'),
        ),
    ]
