# Generated by Django 5.0.6 on 2024-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default=1, max_length=200, verbose_name='Descripcion de producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=4, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
