# Generated by Django 5.0.6 on 2025-05-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0012_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='tarjeta', max_length=20),
        ),
    ]
