# Generated by Django 5.1.4 on 2025-06-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0013_pedido_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('creado', 'Creado'), ('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Pago Rechazado'), ('preparando', 'Preparando orden'), ('despachado', 'Despachado'), ('entregado', 'Entregado')], default='creado', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='transferencia', max_length=20),
        ),
    ]
